server:
  port: 80

spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 500
        show_sql: true
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect


auth:
  jwt:
    issuer : myissue.yoong.com
    secret : 'dsfkghrjhxci139dslfnmw239cxcvn932'
    accessTokenExpirationHour : 168
